_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 41
                - 55
                - 105
            "2":
                - 1
                - 41
                - 55
                - 105
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.5
            "5": 0.18.5
            "8":
                - 1
                - 5
            "12": 0.18.5
            "13": darwin-arm64
channels:
    value: 3
dropout:
    value: 0.5
epochs:
    value: 10
eps:
    value: 1e-06
image_size:
    value: 256
intermediate_size:
    value: 128
lr:
    value: 0.0002
num_heads:
    value: 2
num_hidden_layers:
    value: 12
patch_size:
    value: 8
projection_dim:
    value: 64
test_bs:
    value: 2
train_bs:
    value: 7
